### ISSUE TITLE
api 기술명세서 간단하게 작성해봤는데 피드백좀 부탁드려용

### ISSUE THREAD

**Issue by leeceo97** [prography7-team1-soul/server#2]
@Tnfls99 @PillowCroco 

https://www.figma.com/file/HTEM19RJROliMqLOZrupD5/Soul_test?node-id=0%3A1
디자인 보고 일단 보이는것들 만든거고 알림에 대해서는 내가 내일까지 좀더 알아본다음에 리뷰해줄께!

GET api/clubs : 메인페이지의 IT동아리 리스트 조회
GET api/clubs/:pk : 메인페이지의 IT동아리 상세페이지 조회
POST api/clubs/:pk/bookmark : IT동아리 북마크 취소/ 생성
GET api/chat-rooms: 메인페이지의 오픈톡방 리스트 조회
GET api/chat-rooms/:pk : 메인페이지의 오픈톡방 상세페이지 조회
POST api/char-rooms/:pk/bookmark : 오픈톡방 북마크 취소/ 생성
GET api/articles: 소울러의 후기 리스트 조회
GET api/articles/:pk : 소울러의 후기 상세페이지 조회
POST api/articles/:pk/bookmark : 소울러의 후기 북마크 취소/ 생성

POST api/search : 검색 api  --> 원래는 이걸 GET방식으로 했었는데 POST방식으로 해야한다는 의견이 있었어서 이렇게하긴했어 이부분에 대해서는 한번더 알아볼께!!

POST api/users/signup : 최초 1회 uuid를 통한 회원가입
GET api/users/:pk : 유저 개인페이지 조회
GET api/users/:pk/bookmarks : 유저 북마크 상세 내용

**Comment by Tnfls99** [comment]
빠진 거 없어보입니다!

저번에 얘기했던 것처럼 유저를 내가 하고 동아리, 오픈톡방, 후기 세가지 중 하나 맡고 나머지 두개 오빠가 하는 식으로 하는 건 어떤가요?

**Comment by leeceo97** [comment]
> 빠진 거 없어보입니다!
> 
> 저번에 얘기했던 것처럼 유저를 내가 하고 동아리, 오픈톡방, 후기 세가지 중 하나 맡고 나머지 두개 오빠가 하는 식으로 하는 건 어떤가요?

오키! 그럼 내가 동아리 오픈톡방 맡고 너가 후기랑 유저 맡아볼래?

**Comment by Tnfls99** [comment]
넵! 좋아용

**Comment by leeceo97** [comment]
오킹!!
